#!/bin/bash -x
#Run the command df -h

#This provides information on what disk space is being take up where, crucially the -h flag provides it in human readable format. Percentage and so on.
# This provides information on what disk space is being taken up where.
#As before, the script runs through a series of commands to tidy up some old packages 
#that perhaps have been left lying around or chunks of data that aren't doing anything.
# As before, the script runs through a series of commands to tidy up 
# some old packages that perhaps have been left lying around or chunks 
# of data that aren't doing anything.
# Also note, these scripts are strictly for command line-based operations. 
# There are additional commands to clear space for the desktop versions.
# This script is based on Ubuntu 20.04 LTS distribution.

#Also note, these scripts are strictly for command line based op, there are additional commands to clear space for the desktop versions.

# Based on the ubuntu distribution

########################

# this removes packages that are no longer needed as they have been replaced by newer versions
sudo apt-get autoremove

# cleans the apt-get cache
sudo apt-get clean

# purges old kernels that are no longer in use
sudo apt-get autoremove --purge

# deletes all .deb files from /var/cache/apt/archives. It basically cleans up the apt-get cache
sudo apt-get autoclean
sudo apt-get autoclean

#######################

